glm-4-flashx:
  prompt_template: "glm-4-air/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "glm-4-flashx"
    max_tokens: 8192
  pretty_name: "GLM-4-FlashX"






